<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Varn.Lexer\Varn.Lexer.csproj" />
    <ProjectReference Include="..\..\src\Varn.Modules.Standard\Varn.Modules.Standard.csproj" />
    <ProjectReference Include="..\..\src\Varn.Runtime\Varn.Runtime.csproj" />
  </ItemGroup>
</Project>
